version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080" # Cambia 9000 a 8080 si es necesario

    environment:
      - DB_HOST=ls-e7a7bd71e305d165b4a63a9554551499cc8a816a.c76cmaci05e0.us-west-2.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USER=dbmasteruser
      - DB_PASSWORD=#>uG=1XfhM6|{ctz`WCFeN.wl+fVE>3F
      - DB_NAME=postgres
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}


