version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:8080" # Cambia 9000 a 8080 si es necesario

    environment:
      - DB_HOST=ls-7404b88f97d836aefea18f39df04e8d30c3b1ddb.c2qz5tqa43cm.us-west-2.rds.amazonaws.com
      - DB_PORT=5432
      - DB_USER=dbmasteruser
      - DB_PASSWORD=4L2;nVRf1.:A!-%EQZQ1C}(5aptQxy|u
      - DB_NAME=postgres
      - AWS_REGION=${AWS_REGION}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}


